version: '3.1'

services:
  db:
    container_name: mysql-mocam-dev
    restart: always
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ahzoaelql
    ports:
      - 3308:3306
      
  redis:
    container_name: redis-dev
    image: redis
    ports:
      - 6379
  
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
